import { createFinancialProfileBase, createStarterCategories, createWorkspaceBase } from "../app/defaults";
import type { Category, ImportRecord, IncomeEntry, ReviewItem, Transaction, WorkspaceBundle } from "../../shared/types/models";
import { createId } from "../../shared/utils/id";

export const GUIDE_SAMPLE_FILE_NAME = "가이드 샘플 결제내역.xlsx";
export const GUIDE_SAMPLE_PARSER_ID = "guide-sample-v2";
export const GUIDE_SAMPLE_MEMO = "guide-sample-v2";

function findCategory(categories: Category[], name: string) {
  const category = categories.find((item) => item.categoryType === "category" && item.name === name);
  if (!category) {
    throw new Error(`guide-sample-category-missing:${name}`);
  }
  return category;
}

function createMonthDate(monthOffset: number, day: number) {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth() + monthOffset, day, 12, 0, 0).toISOString();
}

function createMonthKey(monthOffset: number) {
  const now = new Date();
  const date = new Date(now.getFullYear(), now.getMonth() + monthOffset, 1, 12, 0, 0);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

export function createGuideSampleBundle({
  ownerName,
}: {
  ownerName?: string | null;
} = {}): WorkspaceBundle {
  const workspace = createWorkspaceBase("가이드 샘플", "imported");
  const financialProfile = createFinancialProfileBase(workspace.id);
  const categories = createStarterCategories(workspace.id);

  const subscriptionCategory = findCategory(categories, "구독료");
  const foodCategory = findCategory(categories, "식비");
  const cafeCategory = findCategory(categories, "카페");

  const ownerLabel = ownerName?.trim() || "가이드 사용자";
  const person = {
    id: createId("person"),
    workspaceId: workspace.id,
    name: ownerLabel,
    displayName: ownerLabel,
    role: "owner" as const,
    memo: GUIDE_SAMPLE_MEMO,
    isActive: true,
    sortOrder: 0,
    isHidden: false,
  };

  const paymentAccount = {
    id: createId("account"),
    workspaceId: workspace.id,
    ownerPersonId: person.id,
    name: "가이드 카드결제 계좌",
    alias: "카드결제 계좌",
    institutionName: "가이드뱅크",
    accountNumberMasked: "1234",
    accountType: "checking" as const,
    usageType: "card_payment" as const,
    isShared: false,
    memo: GUIDE_SAMPLE_MEMO,
    sortOrder: 0,
    isHidden: false,
  };

  const spendingAccount = {
    id: createId("account"),
    workspaceId: workspace.id,
    ownerPersonId: person.id,
    name: "가이드 생활비 계좌",
    alias: "생활비 계좌",
    institutionName: "가이드뱅크",
    accountNumberMasked: "4321",
    accountType: "checking" as const,
    usageType: "daily" as const,
    isShared: false,
    memo: GUIDE_SAMPLE_MEMO,
    sortOrder: 1,
    isHidden: false,
  };

  const card = {
    id: createId("card"),
    workspaceId: workspace.id,
    ownerPersonId: person.id,
    name: "가이드 메인카드",
    issuerName: "가이드카드",
    cardNumberMasked: "5678",
    linkedAccountId: paymentAccount.id,
    cardType: "credit" as const,
    memo: GUIDE_SAMPLE_MEMO,
    sortOrder: 0,
    isHidden: false,
  };

  const normalizedCategories = categories.map((category) => {
    if (category.id === subscriptionCategory.id || category.id === foodCategory.id || category.id === cafeCategory.id) {
      return {
        ...category,
        linkedAccountId: spendingAccount.id,
      };
    }
    return category;
  });

  const importCurrentId = createId("import");
  const importPrevId = createId("import");
  const importPrev2Id = createId("import");

  const transactions: Transaction[] = [
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      occurredAt: createMonthDate(0, 3),
      settledAt: createMonthDate(0, 3),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "넷플릭스",
      description: "가이드 샘플 - 구독 결제",
      amount: 17000,
      originalAmount: 17000,
      discountAmount: 0,
      categoryId: null,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      occurredAt: createMonthDate(0, 7),
      settledAt: createMonthDate(0, 7),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "동네식당",
      description: "가이드 샘플 - 미분류 결제",
      amount: 23500,
      originalAmount: 23500,
      discountAmount: 0,
      categoryId: null,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      occurredAt: createMonthDate(0, 10),
      settledAt: createMonthDate(0, 10),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "김밥천국",
      description: "가이드 샘플 - 식비 결제",
      amount: 9500,
      originalAmount: 9500,
      discountAmount: 0,
      categoryId: foodCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      occurredAt: createMonthDate(0, 14),
      settledAt: createMonthDate(0, 14),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "가이드카페",
      description: "가이드 샘플 - 카페 결제",
      amount: 6800,
      originalAmount: 6800,
      discountAmount: 0,
      categoryId: cafeCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrevId,
      occurredAt: createMonthDate(-1, 4),
      settledAt: createMonthDate(-1, 4),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "넷플릭스",
      description: "이전 달 구독 결제",
      amount: 17000,
      originalAmount: 17000,
      discountAmount: 0,
      categoryId: subscriptionCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrevId,
      occurredAt: createMonthDate(-1, 11),
      settledAt: createMonthDate(-1, 11),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "동네식당",
      description: "이전 달 식비 결제",
      amount: 31000,
      originalAmount: 31000,
      discountAmount: 0,
      categoryId: foodCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrevId,
      occurredAt: createMonthDate(-1, 18),
      settledAt: createMonthDate(-1, 18),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "가이드카페",
      description: "이전 달 카페 결제",
      amount: 8900,
      originalAmount: 8900,
      discountAmount: 0,
      categoryId: cafeCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrev2Id,
      occurredAt: createMonthDate(-2, 5),
      settledAt: createMonthDate(-2, 5),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "넷플릭스",
      description: "두 달 전 구독 결제",
      amount: 17000,
      originalAmount: 17000,
      discountAmount: 0,
      categoryId: subscriptionCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrev2Id,
      occurredAt: createMonthDate(-2, 12),
      settledAt: createMonthDate(-2, 12),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "마트",
      description: "두 달 전 식비 결제",
      amount: 42800,
      originalAmount: 42800,
      discountAmount: 0,
      categoryId: foodCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
    {
      id: createId("tx"),
      workspaceId: workspace.id,
      importRecordId: importPrev2Id,
      occurredAt: createMonthDate(-2, 22),
      settledAt: createMonthDate(-2, 22),
      transactionType: "expense",
      sourceType: "card",
      ownerPersonId: person.id,
      cardId: card.id,
      accountId: paymentAccount.id,
      fromAccountId: null,
      toAccountId: null,
      merchantName: "가이드카페",
      description: "두 달 전 카페 결제",
      amount: 5400,
      originalAmount: 5400,
      discountAmount: 0,
      categoryId: cafeCategory.id,
      tagIds: [],
      isInternalTransfer: false,
      isExpenseImpact: true,
      isSharedExpense: false,
      refundOfTransactionId: null,
      status: "active",
    },
  ];

  const reviews: ReviewItem[] = [
    {
      id: createId("review"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      reviewType: "category_suggestion",
      status: "open",
      primaryTransactionId: transactions[0]!.id,
      relatedTransactionIds: [],
      confidenceScore: 0.96,
      summary: "반복되는 구독 결제로 보입니다.",
      suggestedCategoryId: subscriptionCategory.id,
    },
    {
      id: createId("review"),
      workspaceId: workspace.id,
      importRecordId: importCurrentId,
      reviewType: "uncategorized_transaction",
      status: "open",
      primaryTransactionId: transactions[1]!.id,
      relatedTransactionIds: [],
      confidenceScore: 0.72,
      summary: "카테고리가 비어 있어 확인이 필요합니다.",
      suggestedCategoryId: null,
    },
  ];

  const imports: ImportRecord[] = [
    {
      id: importCurrentId,
      workspaceId: workspace.id,
      fileName: GUIDE_SAMPLE_FILE_NAME,
      statementMonth: createMonthKey(0),
      importedAt: new Date().toISOString(),
      parserId: GUIDE_SAMPLE_PARSER_ID,
      rowCount: transactions.filter((transaction) => transaction.importRecordId === importCurrentId).length,
      reviewCount: reviews.filter((review) => review.importRecordId === importCurrentId).length,
    },
    {
      id: importPrevId,
      workspaceId: workspace.id,
      fileName: "가이드 이전달 결제내역.xlsx",
      statementMonth: createMonthKey(-1),
      importedAt: new Date().toISOString(),
      parserId: GUIDE_SAMPLE_PARSER_ID,
      rowCount: transactions.filter((transaction) => transaction.importRecordId === importPrevId).length,
      reviewCount: reviews.filter((review) => review.importRecordId === importPrevId).length,
    },
    {
      id: importPrev2Id,
      workspaceId: workspace.id,
      fileName: "가이드 두달전 결제내역.xlsx",
      statementMonth: createMonthKey(-2),
      importedAt: new Date().toISOString(),
      parserId: GUIDE_SAMPLE_PARSER_ID,
      rowCount: transactions.filter((transaction) => transaction.importRecordId === importPrev2Id).length,
      reviewCount: reviews.filter((review) => review.importRecordId === importPrev2Id).length,
    },
  ];

  const incomeEntries: IncomeEntry[] = [
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(0, 1),
      sourceName: "가이드 급여",
      amount: 3200000,
      createdAt: new Date().toISOString(),
    },
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(-1, 1),
      sourceName: "가이드 급여",
      amount: 3200000,
      createdAt: new Date().toISOString(),
    },
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(-2, 1),
      sourceName: "가이드 급여",
      amount: 3150000,
      createdAt: new Date().toISOString(),
    },
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(-3, 1),
      sourceName: "가이드 급여",
      amount: 3150000,
      createdAt: new Date().toISOString(),
    },
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(-4, 1),
      sourceName: "가이드 급여",
      amount: 3100000,
      createdAt: new Date().toISOString(),
    },
    {
      id: createId("income"),
      workspaceId: workspace.id,
      ownerPersonId: person.id,
      occurredAt: createMonthDate(-5, 1),
      sourceName: "가이드 급여",
      amount: 3100000,
      createdAt: new Date().toISOString(),
    },
  ];

  return {
    workspace,
    financialProfile,
    people: [person],
    accounts: [paymentAccount, spendingAccount],
    cards: [card],
    categories: normalizedCategories,
    tags: [],
    transactions,
    reviews,
    imports,
    settlements: [],
    incomeEntries,
  };
}
